### ISSUE TITLE
adding episodes broke build

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/2020-06-03-UCSB-LibCarp#1]
site failed to build after commit 7d6e29d, when Ian dropped new episodes into the workshop from Library Carpentry Webscraping.

**Comment by jonjab** [comment]
![Screen Shot 2020-05-07 at 3 02 24 PM](https://user-images.githubusercontent.com/12768545/81350130-2769b080-9076-11ea-9a20-5853d9190c29.png)

**Comment by jonjab** [comment]
I think episodes were supposed to go in _episodes_rmd

i'm going to try moving them there.

**Comment by jonjab** [comment]
Moving, and totally removing the episode files didn't fix the build.  The above reference commit also had changes to syllabus.html and schedule.html

**Comment by ilessing** [comment]
the error message I saw under github actions is part of the build that we do not control.  It's a github problem I think.
I had success once when I just re-ran the build but that's not reliable either.

----
```
Fetching i18n 0.9.5
11
Errno::EACCES: Permission denied @ rb_file_s_rename -
12
(/home/jekyll/.gem/ruby/2.7.0/cache/i18n-0.9.5.gem,
13
/usr/gem/cache/i18n-0.9.5.gem)
14
An error occurred while installing i18n (0.9.5), and Bundler cannot continue.
```

**Comment by jonjab** [comment]
Jon was hallucinating.  the build never failed.  the gem error here is persistant in different repos.

**Comment by kristi-sara** [comment]
I got it for adding desktrackers into the data folder but its there man

**Comment by jonjab** [comment]
Jon was hallucinating. the build never failed. t
